export interface IBrregEnheterAlle {
    organisasjonsnummer: string;
    navn: string;
    organisasjonsform_kode: string;
    organisasjonsform_beskrivelse: string;
    naringskode_1: string;
    naringskode_1_beskrivelse: string;
    naringskode_2: string;
    naringskode_2_beskrivelse: string;
    naringskode_3: string;
    naringskode_3_beskrivelse: string;
    hjelpeenhetskode: string;
    hjelpeenhetskode_beskrivelse: string;
    antall_ansatte: number;
    hjemmeside: string;
    postadresse_adresse: string;
    postadresse_poststed: string;
    postadresse_postnummer: string;
    postadresse_kommune: string;
    postadresse_kommunenummer: string;
    postadresse_land: string;
    postadresse_landkode: string;
    forretningsadresse_adresse: string;
    forretningsadresse_poststed: string;
    forretningsadresse_postnummer: string;
    forretningsadresse_kommune: string;
    forretningsadresse_kommunenummer: string;
    forretningsadresse_land: string;
    forretningsadresse_landkode: string;
    institusjonell_sektorkode: string;
    institusjonell_sektorkode_beskrivelse: string;
    siste_innsendte_arsregnskap: string;
    registreringsdato_i_enhetsregisteret: string;
    stiftelsesdato: string;
    frivilligregistrertimvaregisteret: string;
    registrert_i_mva_registeret: string;
    registrert_i_frivillighetsregisteret: string;
    registrert_i_foretaksregisteret: string;
    registrert_i_stiftelsesregisteret: string;
    konkurs: string;
    under_avvikling: string;
    under_tvangsavvikling_eller_tvangsopplasning: string;
    overordnet_enhet_i_offentlig_sektor: string;
    malform: string;
};

export interface IOppdaterteEnheter {
    oppdateringsid: number;
    dato: string;
    organisasjonsnummer: string;
    endringstype: string;
    urb_processed: string;
};