
# start this with docker compose up -d
version: '3.8'
services:
  app:
    container_name: shadow-app
    build: app/shadow
    command: ["sh","-c","git clone --no-hardlinks https://github.com/terchris/shadow-brreg  && cd /shadow-brreg/app/shadow && chmod +x ./shadow-appinstall.sh && ./shadow-appinstall.sh"]    
    

#docker exec -it shadow-app sh
# docker container run -it shadow-app /bin/bash


#services:
#  app:
#    container_name: shadow-app
#    image: node:lts-alpine
#    command: ["sh","-c","apk add git && npm install -g typescript && git clone --no-hardlinks https://github.com/terchris/shadow-brreg  && cd /shadow-brreg/app/shadow && chmod +x ./shadow-setup.sh && ./shadow-setup.sh"]    

#docker-compose exec shadow-app sh
#docker exec -ti shadow-app /bin/bash