# start this with docker compose up -d
version: '3.8'
services:
  db:
    container_name: shadow-brreg
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5433"
    ports:
      - '5433:5433'
    volumes:
      - db:/var/lib/postgresql/data
    command: -p 5433
  app:
    container_name: shadow-app
    image: node:lts-alpine
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5433
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=importdata
    volumes:
      - app:/usr/src/app
    command:
      [
        "sh",
        "-c",
        "wget -O shadow-init.sh https://raw.githubusercontent.com/terchris/shadow-brreg/main/shadow-init.sh && chmod +x shadow-init.sh && ./shadow-init.sh"
      ]
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@localhost
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  db:
    driver: local
  app:
    driver: local
  pgadmin:
    driver: local

# to connect to the container: docker exec -ti shadow-app sh 
